kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: multi-scrobbler-secret
    namespace: media
stringData:
    LASTFM_API_KEY: ENC[AES256_GCM,data:ZRM0LygIQwiVu2aEfP86weYjH5yKmS+xB9F02ohSyI4=,iv:QGRE5K89jM+r/vjPSb24/QQK9yJbqgtbwQ4lMwOUGjY=,tag:uNTMw+6wz4l/C9vkHm3Vtw==,type:str]
    LASTFM_SECRET: ENC[AES256_GCM,data:bZr86knpcWM=,iv:t8sumlmG5N+ELlrtTUpEc2iO2IEP7HvVuePLGsZeqzY=,tag:odgcykriPng5dVSxdIkiwA==,type:str]
    KOITO_TOKEN: ENC[AES256_GCM,data:JHURKofjMW3n13ri9i3wxAHRTFoCBysWi1TPEjyixIZGuKWhj6uYsX0YvH3J077p,iv:biIhG7Dpasvv2waQqSYtFnFOHsAyjCTN9kYZHS6M3Og=,tag:eocUTuyS7WlFWYPZtaG6gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b01RTXpocG1XSEcrUG1R
            UWZPZS9aWjRiWEJrNklIbndyWUxjbEJzWEMwClZBVnZBRy81TmpCYzVaMWNHYTdB
            dkNYVktKK0J5SWRPVE5yNWZjcENXdXcKLS0tIENIYy9rRzNvaFUwZGJ0ZDNsQkM0
            NEhmakgwS1pPb0p6RUtia2xRdjlMSkUKCTtmA8N7QCkYWqK6k8MPLCLLOkMw0Px9
            VEtZbshNt7/LUdPDNCbs+LyVNT4F+FNx1w2L/v1/R/2WHLjcrj3hfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T00:03:43Z"
    mac: ENC[AES256_GCM,data:pAqA7ycVjB8779tWLwmbTaShOK7spDefS8d0Gv3G+roNKdrSRpu3kC9KRVQ1wWAlW5FCbhscjxKqHUR9QL0VPLVGKkGEPavfEfu3TLFH57tncOKmwG49fsOY7NJ9Emhwcf+Z7pJCE+jtcBlzV/Aad5VyG6qUSo0PqHHqvKdDhYI=,iv:Da6S1Hvi1UR8V3+Ws3A52nxjZsoGu0JTgccRrpVnXU8=,tag:FpOYe66eHaY5hKxCZD95ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
