kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: multi-scrobbler-secret
    namespace: media
stringData:
    LASTFM_API_KEY: ENC[AES256_GCM,data:jhmFWwZ0YinibBipRvqQW4euB5OdeJP8tga6bb0BM8g=,iv:WdoZk7MSvR4MttDOqaX1C+cV4ZuJevRL3MmijuUFOLw=,tag:FygS8cpgPjPkTFTAxh1uqg==,type:str]
    LASTFM_SECRET: ENC[AES256_GCM,data:4zFC+UxJ/plRIwZ6Hx8tgJ7wKmamLTMs2BFTu2P7hdA=,iv:pF5VY4sJiLx+JzHOeFsk18BXoSIc1MSoQfBUYFkL+UA=,tag:x4Li7J/NyaXReWqhQlXLeg==,type:str]
    KOITO_TOKEN: ENC[AES256_GCM,data:JHURKofjMW3n13ri9i3wxAHRTFoCBysWi1TPEjyixIZGuKWhj6uYsX0YvH3J077p,iv:biIhG7Dpasvv2waQqSYtFnFOHsAyjCTN9kYZHS6M3Og=,tag:eocUTuyS7WlFWYPZtaG6gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b01RTXpocG1XSEcrUG1R
            UWZPZS9aWjRiWEJrNklIbndyWUxjbEJzWEMwClZBVnZBRy81TmpCYzVaMWNHYTdB
            dkNYVktKK0J5SWRPVE5yNWZjcENXdXcKLS0tIENIYy9rRzNvaFUwZGJ0ZDNsQkM0
            NEhmakgwS1pPb0p6RUtia2xRdjlMSkUKCTtmA8N7QCkYWqK6k8MPLCLLOkMw0Px9
            VEtZbshNt7/LUdPDNCbs+LyVNT4F+FNx1w2L/v1/R/2WHLjcrj3hfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T03:40:16Z"
    mac: ENC[AES256_GCM,data:mA/fPXuwouNtNJ6mzhL2eP+guGGrQsRn3Fu/QVNA922nrGWb+SXInG9+S4LM5C9bLT0a3xc3qqVIdlft1Wt3xp8yr3YTP/PwhPCj45CS76lljJZaBI0GAfycUteP5R+sfytcxG+HbU+s437ODUbdWcMQyICqbZssIgKnsoWmKhY=,iv:EM2V2VYJoiQCHsqb9W3+XR1N+fi5XW7fiHVARdYJf1M=,tag:OD3d7f8nFyQroLke3OAVjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
