---
# yaml-language-server: $schema=https://www.schemastore.org/pre-commit-config.json
repos:
  - repo: local
    hooks:
      - id: format
        name: Format files
        entry: task f:format
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        # TODO: Remove once I figure out a better way to handle this
        # They are mandatory empty YAML, which confuses the YAML formatter and the end-of-file-fixer
        exclude: >-
          ^kubernetes/homelab/apps/base/homepage/(external/config/(bookmarks|docker)|internal/config/docker)\.yaml$
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: lint
        name: Lint files
        entry: task l:lint
        language: system
        pass_filenames: false
        always_run: true
