kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: external-dns-unifi-secret
    namespace: networking
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:fVNshoRCHmRfdL0p4XdNTryEXIP5CfeyckECBz7smcw=,iv:XxqsmJ5EzNUv1IK37CzMvYGcAfhXaIOZ7OI60gEldcw=,tag:XA4bg2dmm8dhurYUuuMLEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbExVeFQ0QWhUQmU3bnpY
            eno4b1RQVWJYQjRVZXBBaEtXaVJLcEh4YlNnCmRoVE1uSUFBQ3JiWE5EbkVRa0wx
            SFhJZlVHd3V2WEtYWmIvMEtzalFCZEUKLS0tIHNpQURKR3NqQ3hZMkhKdjkzaUxm
            RTBmWEpKb1ZlMmxvK2hISGlCVS9XTlkKPQROMEB/SO/G1g+jHkxhayBBzSVKp+e7
            w2kgx3AiH4UrGLNN6De8KNBANb+vw0rsvnEL5RNMRf/+NovgfsJihg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T02:07:22Z"
    mac: ENC[AES256_GCM,data:3wavljYmD8jjH4LmUmENrJswjTJh/PvxfrgBfP2m5refXaD8Pz6wfr/CUj+Vl1L65i6BOMDI7yjnVL+RoTQ0LjIUGLYSKvM/iW/jC6Jotq5RjVJbStx55pE8maRThDI8cvqynrnurtqk43qFajD9imd1P8tKGd+VL88brD2EqzE=,iv:D8UMQNUED9JlaBUUeSTB+8FCEI9ifXGMtu2srsl8O+E=,tag:Csy8r2AhXR9Sxgv2GvqY7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
