---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-webhook-token
spec:
  target:
    name: konflate-webhook-token-secret
    template:
      engineVersion: v2
      data:
        KONFLATE_WEBHOOK_SECRET: "{{ .KONFLATE_WEBHOOK_SECRET }}"
  data:
    - secretKey: KONFLATE_WEBHOOK_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ac5df32c-725c-48a9-ac42-b462015913a2
        property: KONFLATE_WEBHOOK_SECRET
