---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: konflate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: konflate
  values:
    config:
      repo: github://ProfMoo/home
    httpRoute:
      enabled: true
      annotations:
        gatus.home-operations.com/endpoint: |-
          conditions: ["[STATUS] == 200"]
      hostnames:
        - konflate.drmoo.io
      parentRefs:
        - name: envoy-external
          namespace: networking
          sectionName: https
    monitoring:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 1Gi
    secret:
      existingSecret: konflate-webhook-token-secret
