---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nut-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nut-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nut-server
    spec:
      priorityClassName: high-priority
      enableServiceLinks: false
      containers:
        - name: nut-upsd
          image: instantlinux/nut-upsd:2.8.3-r4@sha256:ab2f9988309ee8a47934e03eb836fa5313cc34234f50ea5400ec65c71dd4e0b2
          ports:
            - name: nut
              containerPort: 3493
              protocol: TCP
          env:
            - name: NAME
              value: rack
            - name: DRIVER
              value: snmp-ups
            - name: SERVER
              value: primary
            - name: API_USER
              value: upsmon
          readinessProbe:
            tcpSocket:
              port: nut
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: nut
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: nut-local-config
              mountPath: /etc/nut/local/ups.conf
              subPath: ups.conf
            - name: nut-local-config
              mountPath: /etc/nut/local/upsd.conf
              subPath: upsd.conf
            - name: nut-local-config
              mountPath: /etc/nut/local/upsd.users
              subPath: upsd.users
            - name: nut-local-config
              mountPath: /etc/nut/local/upsmon.conf
              subPath: upsmon.conf
      volumes:
        - name: nut-local-config
          secret:
            secretName: nut-server-config
