---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nut-server
spec:
  target:
    name: nut-server-config
    template:
      engineVersion: v2
      data:
        ups.conf: |
          [rack]
            driver = snmp-ups
            port = 192.168.1.49
            mibs = eaton_pw_nm2
            snmp_version = v3
            secLevel = authPriv
            secName = {{ .SNMPV3_USERNAME }}
            authProtocol = SHA256
            authPassword = {{ .SNMPV3_AUTH_PASSWORD }}
            privProtocol = AES256
            privPassword = {{ .SNMPV3_PRIV_PASSWORD }}
            pollfreq = 15
            desc = "Rack UPS"
        upsd.conf: |
          LISTEN 0.0.0.0 3493
        upsd.users: |
          [upsmon]
            password = {{ .UPSD_PASSWORD }}
            upsmon primary
            actions = fsd
        upsmon.conf: |
          MONITOR rack@localhost 1 upsmon {{ .UPSD_PASSWORD }} primary
          RUN_AS_USER nut
          SHUTDOWNCMD "/bin/true"
          FINALDELAY 5
  data:
    - secretKey: SNMPV3_USERNAME
      sourceRef: &sourceRef
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1973b157-3746-4656-8c78-b46f00ea1f2f
        property: READONLY_USERNAME
    - secretKey: SNMPV3_AUTH_PASSWORD
      sourceRef: *sourceRef
      remoteRef:
        key: 1973b157-3746-4656-8c78-b46f00ea1f2f
        property: READONLY_PASSWORD
    - secretKey: SNMPV3_PRIV_PASSWORD
      sourceRef: *sourceRef
      remoteRef:
        key: 1973b157-3746-4656-8c78-b46f00ea1f2f
        property: READONLY_PASSWORD
    - secretKey: UPSD_PASSWORD
      sourceRef: *sourceRef
      remoteRef:
        key: 1973b157-3746-4656-8c78-b46f00ea1f2f
        property: UPSD_PASSWORD
