---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-router
spec:
  chartRef:
    kind: OCIRepository
    name: mc-router
  interval: 15m
  values:
    image:
      repository: ghcr.io/itzg/mc-router
      tag: 1.46.4@sha256:92766cd72262e4e13569463708af2bb87457ee5b3ba914b72ccbc8b09f8eb384
      pullPolicy: IfNotPresent
    services:
      minecraft:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.8.134
