---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-router
spec:
  chartRef:
    kind: OCIRepository
    name: mc-router
  interval: 15m
  values:
    image:
      repository: ghcr.io/itzg/mc-router
      tag: 1.47.1@sha256:177433dd91507339924d60205a19ae9a289afd0e69dbad54e1a55d497f7523f8
      pullPolicy: IfNotPresent
    services:
      minecraft:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.8.134
