---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-router
spec:
  chartRef:
    kind: OCIRepository
    name: mc-router
  interval: 15m
  values:
    image:
      repository: ghcr.io/itzg/mc-router
      tag: 1.45.4@sha256:1ffcbfe6fa01a73b61f351fd2b30c124838975e03dd65a5d4a272cc30bdd4dd7
      pullPolicy: IfNotPresent
    services:
      minecraft:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.8.134
