---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        ALERTMANAGER_HEARTBEAT_URL: "{{ .ALERTMANAGER_HEARTBEAT_URL }}"
        ALERTMANAGER_NTFY_WEBHOOK_USERNAME: alertmanager
        ALERTMANAGER_NTFY_WEBHOOK_PASSWORD: verysecure
  data:
    - secretKey: ALERTMANAGER_HEARTBEAT_URL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 79798ce5-21a2-4887-965e-b31d002752af
        property: ALERTMANAGER_HEARTBEAT_URL
