---
version: "3"
tasks:
  format:
    desc: "Run all formatters"
    deps:
      - format-yaml
      - format-markdown
      - format-hcl
      - format-shell
  format-yaml:
    desc: "Format YAML files"
    cmds:
      - echo "==> Formatting YAML files..."
      - yamlfmt -conf .yamlfmt.yaml
      - echo "==> Done formatting YAML files"
  format-markdown:
    desc: "Format Markdown files"
    cmds:
      - echo "==> Formatting Markdown files..."
      - markdownlint-cli2 --config .markdownlint-cli2.yaml "**/*.md" --fix
      - echo "==> Done formatting Markdown files"
  format-hcl:
    desc: "Format HCL files"
    cmds:
      - echo "==> Formatting HCL files..."
      - tofu fmt -recursive
      - echo "==> Done formatting HCL files"
  format-shell:
    desc: "Format Shell scripts"
    cmds:
      - echo "==> Formatting shell scripts..."
      - shfmt --write .
      - echo "==> Done formatting shell scripts"
