---
address: 0.0.0.0
port: 9348
timeout: 30
concurrency: 2
hosts:
  node-2.internal.drmoo.io:
    username: ADMIN
    password: ADMIN
  node-3.internal.drmoo.io:
    username: ADMIN
    password: ADMIN
  node-1.internal.drmoo.io:
    username: root
    password: calvin
    use_basic_auth: true
metrics:
  all: false
  system: true
  sensors: true
  power: true
  processors: true
  events: true
  storage: false
  memory: true
  network: true
  manager: true
  extra: true
events:
  severity: warning
  maxage: 7d
