---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-secret
spec:
  target:
    name: hermes-secret
    template:
      engineVersion: v2
      data:
        API_SERVER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
  refreshInterval: 15m
  data:
    - secretKey: LITELLM_MASTER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 590c2ca8-8f90-4fd7-b80a-b4850169f2bb
        property: LITELLM_MASTER_KEY
