---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-email-secret
spec:
  target:
    name: hermes-email-secret
    template:
      engineVersion: v2
      data:
        EMAIL_ADDRESS: "{{ .EMAIL_ADDRESS }}"
        EMAIL_PASSWORD: "{{ .EMAIL_PASSWORD }}"
  refreshInterval: 15m
  data:
    - secretKey: EMAIL_ADDRESS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 85ccadd4-2e1e-429f-a071-b4ab0027f5cc
        property: EMAIL_ADDRESS
    - secretKey: EMAIL_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 85ccadd4-2e1e-429f-a071-b4ab0027f5cc
        property: EMAIL_PASSWORD
