---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: internal-node-2
spec:
  endpoints:
    - dnsName: internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.8.131"]
    - dnsName: k8s.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.8.99"]
    - dnsName: node.1.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.120"]
    - dnsName: node.2.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.112"]
    - dnsName: node.3.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.187"]
    - dnsName: pve.1.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.64"]
    - dnsName: pve.2.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.67"]
    - dnsName: pve.4.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.66"]
    - dnsName: pve.5.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.48"]
    - dnsName: truenas.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.26"]
    - dnsName: truenas-oobm.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.54"]
    - dnsName: unifi.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.1"]
    - dnsName: ups.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.49"]
    - dnsName: zigbee.internal.drmoo.io
      recordType: A
      recordTTL: 300
      targets: ["192.168.1.148"]
