---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: anime-radarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn:
    - name: rook-ceph-cluster
      namespace: storage
  values:
    controllers:
      anime-radarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.2.1@sha256:0756fffa75b30219e3dbac8d027a5389f53cbb34ae83fa4b0976c1b0524c8eb1
            env:
              RADARR__APP__INSTANCENAME: Anime Radarr
              RADARR__APP__THEME: dark
              RADARR__AUTH__APIKEY: "foobarbazfoobarbazfoobarbazfooba"
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__LOG__LEVEL: info
              RADARR__SERVER__PORT: &port 80
              TZ: America/New_York
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
    service:
      app:
        controller: anime-radarr
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Anime movie torrent manager (admin:admin)
          gethomepage.dev/group: Torrents
          gethomepage.dev/icon: radarr.png
          gethomepage.dev/name: Anime Radarr
          gethomepage.dev/instance: homepage-internal
          gethomepage.dev/widget.type: "radarr"
          gethomepage.dev/widget.url: "http://anime-radarr.media.svc.cluster.local:80"
          gethomepage.dev/widget.key: "foobarbazfoobarbazfoobarbazfooba"
        hostnames:
          - "anime-radarr.drmoo.io"
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
    persistence:
      config:
        existingClaim: anime-radarr-blockstorage
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: 192.168.8.248
        path: /mnt/vault/media
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
