---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secret
spec:
  target:
    name: litellm-secret
    template:
      engineVersion: v2
      data:
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
  refreshInterval: 15m
  data:
    - secretKey: LITELLM_MASTER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 590c2ca8-8f90-4fd7-b80a-b4850169f2bb
        property: LITELLM_MASTER_KEY
    - secretKey: ANTHROPIC_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 590c2ca8-8f90-4fd7-b80a-b4850169f2bb
        property: ANTHROPIC_API_KEY
    - secretKey: OPENAI_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 590c2ca8-8f90-4fd7-b80a-b4850169f2bb
        property: OPENAI_API_KEY
