#!/bin/bash

# Delete old nodes directory
rm -r nodes

# Create nodes directory
mkdir nodes

# Get the worker node configs from the tofu output
# and write them to individual files
tofu output -json worker_node_configs |
	jq -rc 'to_entries[]' |
	while IFS= read -r entry; do
		key=$(echo "$entry" | jq -r '.key')
		value=$(echo "$entry" | jq -r '.value')
		echo "$value" >"nodes/${key}.yaml"
	done

# Get the control plane configs from the tofu output
# and write them to individual files
tofu output -json control_plane_configs |
	jq -rc 'to_entries[]' |
	while IFS= read -r entry; do
		key=$(echo "$entry" | jq -r '.key')
		value=$(echo "$entry" | jq -r '.value')
		echo "$value" >"nodes/${key}.yaml"
	done
