kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: koito-secrets
    namespace: media
stringData:
    KOITO_LASTFM_API_KEY: ENC[AES256_GCM,data:DxjwndDqg6FLwqH+U5EUWT+zLrXOJpF+hLMi5Ly78SY=,iv:i25vHFNRdMFFn5ljCRDiIucZ3H28zXa4J1gk2VRfnp4=,tag:fWmqyslfB4T44tK10wbyCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVWppTWRHdGFwYStldFZj
            MGlCTG44U1pzU2dpcS9FUlVwdGlJb2xLYlQ0CjlvQmVWV1JDRHJRODh4SStXS3F1
            NmNicEdtWG1WanU2d0M2VFhxVzNac2MKLS0tIFNSNFpGc3cyNEI1TytpeXpPTWd3
            TWlLbG5HZ1Y4OGdxcjcxdnBzaE9oQzAK3QWQllbkPddSGGO5PT4+sWnHorDVU6wO
            NnLiVfteZgcR1nmqlxOX3rlm8vbQn1exqmbQQd5GlQ2MjWgfGAsvVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T22:35:54Z"
    mac: ENC[AES256_GCM,data:TV/J0AF0patf9b3lzZZ7VHtPiVbFQ44U5LbdYvkL5FMGuoxghF2NXSHY4AF1Gntd+XulZAvqjAEa9U0OD8m+Zj7+vI1I5Sw08uTlPTf4s1FyAgdd9F6/JS2rJSIqPwoq0xX5VRjAzdevtokhKcLOkpW5DQRjCa+G0nhaIdoneaY=,iv:QUFtBVf1zi+h9LvcAmjYBGxVf+ja79OMeQiI06z59x8=,tag:EsTjD/QG08lhcJEtCUXkVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
