kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: external-dns-unifi-secret-static
    namespace: networking
stringData:
    EXTERNAL_DNS_UNIFI_USER: ENC[AES256_GCM,data:VTViKC8=,iv:hAUeoPqbBkpVIRGgLQxJmDJmCQCRzkc2K0/iAMIqisY=,tag:auSvB0x33urm9wWhn9Bwdg==,type:str]
    EXTERNAL_DNS_UNIFI_PASS: ENC[AES256_GCM,data:FGI+bvRfPPKqGRU5kyr8FgED7zA9Hez+wQ==,iv:lRVmDZOryoGI7BTcaneswbPzKTFp2FYmJTJlSc/mPmg=,tag:7Ls9DgROvRiW282/ZNfsbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbExVeFQ0QWhUQmU3bnpY
            eno4b1RQVWJYQjRVZXBBaEtXaVJLcEh4YlNnCmRoVE1uSUFBQ3JiWE5EbkVRa0wx
            SFhJZlVHd3V2WEtYWmIvMEtzalFCZEUKLS0tIHNpQURKR3NqQ3hZMkhKdjkzaUxm
            RTBmWEpKb1ZlMmxvK2hISGlCVS9XTlkKPQROMEB/SO/G1g+jHkxhayBBzSVKp+e7
            w2kgx3AiH4UrGLNN6De8KNBANb+vw0rsvnEL5RNMRf/+NovgfsJihg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T02:48:41Z"
    mac: ENC[AES256_GCM,data:smGMNEauYcLO6H2a9hc5uAUVmi7l7ayNVj5qYHMi8wu6lED0RRMTF2nbj8+a9LyuVL9+cJIGY0wzBmZmoyJnCoRPDynEuTkvQ9ePEcosS20LoEbLF7tMazQQqBm5CwFVqyvrR+rxgmeAjMLabxjUlA7HuadHLxBrUsxY1TQUx1M=,iv:zxrGMTUNSUNYJhWT5LOeTqrdg0liUnbIKHS0hCZG2As=,tag:6C4sKSY8HBc98LI7NT08Mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
