kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: external-dns-unifi-secret-static
    namespace: networking
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:mAp5DMopI9Oxx1eZHK+bn2zXe+IZgKGl1dv+CrYr5dA=,iv:NO23y3IAVd7SFZAsVQFWu9Lam+vvq1ddVpqPFWC3nj4=,tag:ZuxJzIOTNwEAEvaGlEIu8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbExVeFQ0QWhUQmU3bnpY
            eno4b1RQVWJYQjRVZXBBaEtXaVJLcEh4YlNnCmRoVE1uSUFBQ3JiWE5EbkVRa0wx
            SFhJZlVHd3V2WEtYWmIvMEtzalFCZEUKLS0tIHNpQURKR3NqQ3hZMkhKdjkzaUxm
            RTBmWEpKb1ZlMmxvK2hISGlCVS9XTlkKPQROMEB/SO/G1g+jHkxhayBBzSVKp+e7
            w2kgx3AiH4UrGLNN6De8KNBANb+vw0rsvnEL5RNMRf/+NovgfsJihg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T02:07:29Z"
    mac: ENC[AES256_GCM,data:yktUZ1cM46uEUexxNZBQHAXCFUHcd6pHLzfFmmeR9qg8CiYDx7qiAqSJFsv5mcgP8kNcE0c+5RBP8sEVbMFuNFAZjuoCAyJEqYs9jvqWmwcJwpIUlOam2zp+fNCkOtBsT8UNJ7ZrL7+hg8qhi647exm1cPLbptDR7m9fxdz2Yds=,iv:KN/8cd63hrpAutruAm1vpEMccHfLobyrPbYALJ9MstA=,tag:Tl7azv6Ubv7f4TuWmWqThg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
